language: php

php:
  - 5.6
  - 7.0

sudo: true

env:
  global:
    - PHPCS=0
    - RUN_TESTS=1

matrix:
  include:
    - php: 5.6
      env: PHPCS=1 RUN_TESTS=0

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.0/elasticsearch-2.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart

install:
  - composer self-update
  - composer install --dev

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
